"""added user surname

Revision ID: 1bccd8f8c094
Revises: 76b6bbb0d99f
Create Date: 2023-10-20 01:22:11.956750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bccd8f8c094'
down_revision: Union[str, None] = '76b6bbb0d99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('surname', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'surname')
    # ### end Alembic commands ###
